spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/app
      username: postgres
      password: pwd
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect